/* ============================================================
   작가 정보, CV, 작품 목록
   ------------------------------------------------------------
   이 파일만 수정하면 사이트의 내용이 바뀝니다.
   이미지 파일은 images 폴더에 넣은 뒤, 아래 image 경로를 맞춰 주세요.
   ============================================================ */

const ARTIST = {
  name: "허규",
  nameKo: "HEU GYU",
  location: "Busan, Korea",
  email: "https://brunch.co.kr/@quetzal",
  instagram: "https://www.instagram.com/0131_q/",
  siteTitle: "허규",
  statement: [
    "\"살아 있기 때문에 그린다.\"",
    "연약하면서도 질긴 하나의 생명을 가지고, 소소하고 보잘것없는 세계 속에서 아름다움과 즐거움을 발견하기 위해, 그렇게 살아 있기 위해서 그린다.",
    "나는 내가 발견한 것을 하나의 정답으로 제시하고 싶지 않다. 작품을 마주한 사람이 자신의 감각과 생각으로 경험하고, 각자의 방식으로 무언가를 발견하기를 바란다.",
    "이러한 태도에서 출발해 이미지가 물질과 공간을 만나며 어떻게 감각되고 경험되는지에 관심을 두고 작업한다. 수묵과 드로잉을 비롯해 입체, 사진, 게임 인터랙티브 아트 등 다양한 매체를 오가며 이미지와 물질, 공간 사이의 관계를 탐구한다.",
    "작품을 통해 일방적으로 말하기보다, 서로 다른 감각과 해석이 공존하는 전시 공간을 관객과 함께 만들어 가고 싶다.",
  ],
  bio: "",
};

/* Artist CV
   - year: 연도 또는 기간 (예: 2024, 2022–2024, 2022–현재). 비워 두면 연도 칸이 숨겨집니다.
   - title: 학교 / 학위 / 상 이름 / 전시명 / 프로그램명 / 역할
   - place: 학교, 기관, 장소 (한 줄)
   - lines: 선택. 학위·전공·업무 내용처럼 제목/장소 아래 여러 줄
   - note: 선택. 전시의 Solo, Group 같은 짧은 표시
*/
const CV = {
  education: [
    {
      title: "Hongik University, Korea",
      lines: [
        "B.F.A., School of Film and Animation",
        "Double Major in Oriental Painting",
      ],
    },
    {
      title: "Kyoto University of the Arts, Japan",
      lines: ["Exchange Student, Department of Information Design"],
    },
  ],
  awards: [
    { year: "2026", title: "Grand Prize, Withers Career Dream Speech Competition" },
    { year: "2025", title: "Jury Award, GameAlfy AI-Based Game Creation Competition" },
    {
      year: "2024",
      title: "Grand Prize, My Successful Department Entry Essay Competition",
      place: "Hongik University",
    },
  ],
  exhibitions: [
    {
      year: "2024",
      title: "Graduation Exhibition, Department of Oriental Painting, Hongik University",
      place: "Seoul, Korea",
    },
  ],
  projects: [
    {
      year: "2026",
      title: "Open Circuit Busan: Art & Tech Practice",
      place: "Busan Cultural Foundation, Busan, Korea",
    },
  ],
  experience: [
    {
      year: "2022",
      title: "IDENID — Intern",
      place: "Seoul, Korea",
      lines: [
        "Planned and produced video content",
        "Developed and created video projects",
      ],
    },
  ],
};

/* 작품 분류
   - id: 영문 짧은 이름 (주소에 쓰입니다)
   - label: 화면에 보이는 이름
   - layout: "large" 크게 한 장씩 / "grid" 여러 칸 그리드
   나중에 입체, 드로잉, 사진, Game을 넣으려면 아래처럼 한 줄을 추가하면 됩니다.
   { id: "sculpture", label: "Sculpture / 입체", layout: "large" },
   { id: "drawing", label: "Drawing / 드로잉", layout: "grid" },
   { id: "photo", label: "Photography / 사진", layout: "grid" },
   { id: "game", label: "Game", layout: "grid" },
*/
const CATEGORIES = [
  { id: "ink", label: "Ink / 수묵", layout: "large" },
  { id: "painting", label: "Painting / 회화", layout: "large" },
  { id: "sculpture", label: "Sculpture / 입체", layout: "sculpture" },
  { id: "drawing", label: "Drawing / 드로잉", layout: "float" },
  { id: "photo", label: "Photography / 사진", layout: "grid" },
  { id: "video", label: "Video / 영상", layout: "video" },
  { id: "game", label: "Game / 게임", layout: "game" },
];

/* 작품 목록
   - id: 작품마다 겹치지 않는 영문/숫자 이름
   - category: 위의 CATEGORIES id와 같게
   - order: 같은 분류 안에서의 순서 (작은 숫자가 먼저)
   - type: 선택. "view"는 전시전경처럼 작품이 아닌 설치 사진
   - title, year, medium, size, description: 비워 두면 화면에 안 나옵니다. 나중에 직접 적으면 됩니다.
   - image: images 폴더 안 파일 경로
   - video: 선택. 영상 파일 경로 (파일명은 그대로 둡니다)
   - url: 선택. Game처럼 외부 링크로 바로 열 때
   - images: 선택. [왼쪽, 오른쪽, 오른쪽 hover] 같은 작품의 사진이 여러 장일 때
*/
const WORKS = [
  {
    id: "ink-01",
    category: "ink",
    order: 1,
    title: "生 Live",
    year: "2024",
    medium: "한지 콜라주 수묵",
    size: "160 × 210 cm",
    description: "",
    image: "images/ink/01.jpg",
  },
  {
    id: "ink-02",
    category: "ink",
    order: 2,
    compact: true,
    title: "살아간다는 것은",
    year: "2024",
    medium: "순지에 수묵",
    size: "144 × 75 cm",
    description: "",
    image: "images/ink/02.jpg",
  },
  {
    id: "ink-03",
    category: "ink",
    order: 3,
    compact: true,
    title: "살아간다는 것은",
    year: "2024",
    medium: "순지에 수묵",
    size: "144 × 75 cm",
    description: "",
    image: "images/ink/03.jpg",
  },
  {
    id: "ink-04",
    category: "ink",
    order: 4,
    compact: true,
    title: "살아간다는 것은",
    year: "2024",
    medium: "순지에 수묵",
    size: "144 × 75 cm",
    description: "",
    image: "images/ink/04.jpg",
  },
  {
    id: "ink-05",
    category: "ink",
    order: 7,
    wide: true,
    title: "마음",
    year: "2021",
    medium: "화선지에 수묵",
    size: "35 × 35 cm",
    description: "",
    image: "images/ink/05.jpg",
  },
  {
    id: "ink-06",
    category: "ink",
    order: 5,
    title: "마음",
    year: "2021",
    medium: "화선지에 수묵",
    size: "35 × 35 cm",
    description: "",
    image: "images/ink/06.jpg",
  },
  {
    id: "ink-07",
    category: "ink",
    order: 6,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/ink/07.jpg",
  },
  {
    id: "ink-exhibition",
    category: "ink",
    order: 8,
    type: "view",
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/ink/exhibition-view.jpg",
  },
  {
    id: "painting-01",
    category: "painting",
    order: 1,
    title: "In no Time",
    year: "2025",
    medium: "캔버스에 아크릴",
    size: "90.9 × 72.7 cm",
    description: "",
    image: "images/painting/01.jpg?v=3",
  },
  {
    id: "painting-02",
    category: "painting",
    order: 2,
    title: "낙하",
    year: "2025",
    medium: "캔버스에 아크릴",
    size: "60.6 × 72.7 cm",
    description: "",
    image: "images/painting/02.jpg",
  },
  {
    id: "painting-03",
    category: "painting",
    order: 3,
    title: "해울",
    year: "2026",
    medium: "종이에 아크릴",
    size: "45.5 × 38 cm",
    description: "",
    image: "images/painting/03.jpg",
  },
  {
    id: "sculpture-01",
    category: "sculpture",
    order: 1,
    title: "Belonging",
    year: "2023",
    medium: "물티슈, 파스텔",
    size: "110 × 120 cm",
    description: "",
    image: "images/sculpture/입체 01.jpg",
    images: ["images/sculpture/입체 01.jpg"],
  },
  {
    id: "sculpture-02",
    category: "sculpture",
    order: 2,
    title: "부산",
    year: "2021",
    medium: "철사",
    size: "50 × 34 cm",
    description: "",
    image: "images/sculpture/입체 02 (2).jpg",
    images: [
      "images/sculpture/입체 02 (2).jpg",
      "images/sculpture/입체 03.jpg",
    ],
  },
  {
    id: "drawing-01",
    category: "drawing",
    order: 1,
    title: "入口",
    year: "2021",
    medium: "혼합재료",
    size: "39 × 27 cm",
    description: "",
    image: "images/drawing/入口 39x27 cm 혼합재료 2021.jpg",
  },
  {
    id: "drawing-02",
    category: "drawing",
    order: 2,
    title: "哀",
    year: "2021",
    medium: "연필",
    size: "21 × 30 cm",
    description: "",
    image: "images/drawing/哀 21 X 30cm 鉛筆 연필 2021.jpg",
  },
  {
    id: "drawing-03",
    category: "drawing",
    order: 3,
    title: "가을잠",
    year: "2022",
    medium: "화선지에 수묵",
    size: "65 × 50 cm",
    description: "",
    image: "images/drawing/가을잠 2022 화선지에 수묵65x50cm.jpg",
  },
  {
    id: "drawing-04",
    category: "drawing",
    order: 4,
    title: "가티",
    year: "2023",
    medium: "화선지에 수묵",
    size: "35 × 30 cm",
    description: "",
    image: "images/drawing/가티 2023화선지에 수묵35x30cm.jpg?v=2",
  },
  {
    id: "drawing-05",
    category: "drawing",
    order: 5,
    title: "그만두게 된 것",
    year: "2023",
    medium: "화선지에 수묵",
    size: "35 × 30 cm",
    description: "",
    image: "images/drawing/그만두게 된 것 2023화선지에 수묵 35x30cm.jpg",
  },
  {
    id: "drawing-06",
    category: "drawing",
    order: 6,
    title: "마주침",
    year: "2023",
    medium: "화선지에 수묵",
    size: "60 × 30 cm",
    description: "",
    image: "images/drawing/마주침 2023 화선지에 수묵60x30cm.jpg",
  },
  {
    id: "drawing-07",
    category: "drawing",
    order: 7,
    title: "별바람",
    year: "2021",
    medium: "연필",
    size: "30 × 21 cm",
    description: "",
    image: "images/drawing/별바람 30x21cm 연필 2021.jpg",
  },
  {
    id: "drawing-08",
    category: "drawing",
    order: 8,
    title: "선잠",
    year: "2023",
    medium: "화선지에 수묵",
    size: "35 × 30 cm",
    description: "",
    image: "images/drawing/선잠 - 화선지에 수묵 35x30cm 2023.jpg",
  },
  {
    id: "drawing-09",
    category: "drawing",
    order: 9,
    title: "숨",
    year: "2022",
    medium: "화선지에 수묵",
    size: "65 × 50 cm",
    description: "",
    image: "images/drawing/숨 2022 화선지에 수묵65x50cm (2).jpg",
  },
  {
    id: "drawing-10",
    category: "drawing",
    order: 10,
    title: "시선",
    year: "2023",
    medium: "화선지에 먹",
    size: "35 × 30 cm",
    description: "",
    image: "images/drawing/시선 2023 화선지에 먹 35x30cm.jpg",
  },
  {
    id: "drawing-11",
    category: "drawing",
    order: 11,
    title: "시선",
    year: "2023",
    medium: "화선지에 먹",
    size: "35 × 30 cm",
    description: "",
    image: "images/drawing/시선 2023 화선지에 먹 35x30cm (2).jpg",
  },
  {
    id: "drawing-12",
    category: "drawing",
    order: 12,
    title: "시선",
    year: "2023",
    medium: "화선지에 먹",
    size: "35 × 30 cm",
    description: "",
    image: "images/drawing/시선 2023 화선지에 먹 35x30cm (3).jpg",
  },
  {
    id: "drawing-13",
    category: "drawing",
    order: 13,
    title: "응시",
    year: "2022",
    medium: "화선지에 수묵",
    size: "65 × 50 cm",
    description: "",
    image: "images/drawing/아기새 2022 화선지에 수묵65x50cm.jpg",
  },
  {
    id: "drawing-14",
    category: "drawing",
    order: 14,
    title: "유희",
    year: "2022",
    medium: "화선지에 수묵",
    size: "65 × 50 cm",
    description: "",
    image: "images/drawing/유희 2022 화선지에 수묵65x50cm.jpg",
  },
  {
    id: "drawing-15",
    category: "drawing",
    order: 15,
    title: "자유낙하",
    year: "2023",
    medium: "화선지에 수묵",
    size: "35 × 30 cm",
    description: "",
    image: "images/drawing/자유낙하 화선지에 수묵 35x30cm 2023.jpg",
  },
  {
    id: "drawing-16",
    category: "drawing",
    order: 16,
    title: "친구",
    year: "2021",
    medium: "연필",
    size: "30 × 21 cm",
    description: "",
    image: "images/drawing/친구 30x21cm 鉛筆 연필 2021.jpg?v=2",
  },
  {
    id: "drawing-17",
    category: "drawing",
    order: 17,
    title: "콩의 공간",
    year: "2021",
    medium: "연필",
    size: "30 × 21 cm",
    description: "",
    image: "images/drawing/콩의 공간 30x21cm 연필 2021.jpg?v=2",
  },
  {
    id: "photo-01",
    category: "photo",
    order: 1,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715_07.jpg",
  },
  {
    id: "photo-02",
    category: "photo",
    order: 2,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715.jpg",
  },
  {
    id: "photo-03",
    category: "photo",
    order: 3,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715_03.jpg",
  },
  {
    id: "photo-04",
    category: "photo",
    order: 4,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20250619_224300012.jpg",
  },
  {
    id: "photo-05",
    category: "photo",
    order: 5,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715_05.jpg",
  },
  {
    id: "photo-06",
    category: "photo",
    order: 6,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715_06.jpg",
  },
  {
    id: "photo-07",
    category: "photo",
    order: 7,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715_01.jpg",
  },
  {
    id: "photo-08",
    category: "photo",
    order: 8,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715_04.jpg?v=2",
  },
  {
    id: "photo-09",
    category: "photo",
    order: 9,
    title: "",
    year: "",
    medium: "",
    size: "",
    description: "",
    image: "images/photo/KakaoTalk_20260906_144939715_02.jpg",
  },
  {
    id: "video-01",
    category: "video",
    order: 1,
    title: "숨",
    year: "2022",
    medium: "Video",
    size: "6초",
    description: "",
    image: "images/video/숨 Video 2022 6sec.jpg",
    video: "videos/숨 Video 2022 6sec.mp4",
  },
  {
    id: "video-03",
    category: "video",
    order: 2,
    title: "Long Day of Long Ice Coffee",
    year: "2022",
    medium: "",
    size: "",
    description: "",
    image: "images/video/Long Day of Long Ice Coffee.jpg",
    video: "videos/Long Day of Long Ice Coffee.mp4",
  },
  {
    id: "video-02",
    category: "video",
    order: 3,
    title: "저물다",
    year: "2022",
    medium: "Video",
    size: "42초",
    description: "",
    image: "images/video/저물다 Video 2022 42sec.jpg",
    video: "videos/저물다 Video 2022 42sec.mp4",
  },
  {
    id: "video-04",
    category: "video",
    order: 4,
    title: "As a Chive blossom",
    year: "2026",
    medium: "",
    size: "",
    description: "",
    image: "images/video/As a Chive blossom _Q.jpg",
    video: "videos/As a Chive blossom _Q.mp4",
  },
  {
    id: "game-01",
    category: "game",
    order: 1,
    title: "신:별주부전",
    year: "",
    medium: "",
    size: "",
    description: "디지털게임 기획 연출 디자인 2025",
    image: "images/game/KakaoTalk_20260906_144908308.png",
    url: "https://www.game-ping.kr/games/000627",
  },
];

